 @startuml test
 hide circle
 skinparam linetype ortho

 entity "users (ユーザー)" as users {
    ' * 表示修飾子は必須属性を表します。 空白を1文字後ろに入れることで、強調{**}と解釈されることを防ぐと良いでしょう:
     * <<PK>> user_id
     --
     * name: string : ユーザー名
     --
     unique : [user_id]
 }

 entity "purchases (購入履歴)" as purchases {
     * <<PK>> purchase_id
     --
     * <<FK>> user_id
     * <<FK>> product_id
     * purchase_date_time
     * quantity
     --
     unique : [purchase_id]
 }

 entity "products (製品)" as products {
     * <<PK>> product_id
     --
     * product_name
     * <<FK>> category_id
     * price
     * stock_quantity
 }

 entity "categories (商品分類)" as categories {
     * <<PK>> category_id
     --
     * category_name
 }

 users ||--o{ purchases
 purchases ||..o{ products
 categories ||--o{ products
 @enduml