' 表記ルール
' 頭には主キーを記載し -- で区切る
' <<FK>> 外部キー
' <<u>> ユニークキー
' カラム名 : 型 : 説明 を書く
' 複合ユニークなど特別な記載は -- で更に区切って記述
' * 表示修飾子は必須属性を表します。 空白を1文字後ろに入れることで、強調{**}と解釈されることを防ぐと良いでしょう:

@startuml internet_tv
hide circle
hide empty members
skinparam linetype ortho

entity program_slots {
    channel_name
    start_time
    end_time
    --
    <<FK>> title_name
    <<FK>> season_num
    <<FK>> episode_num
}

entity programs {
    title_name
    season_num
    --
    <<FK>> genre_id
    detail
}

entity genre {
    genre_id
    genre_name
}

entity episodes {
    <<FK>> title_name
    <<FK>> season_num
    episode_num
    --
    episode_name
    episode_details
    released_ad
    video_duration
    viewer
}

program_slots }|--|| programs
genre }|--|| programs
episodes ||--|| program_slots
@endumls