 @startuml test
 hide circle
 skinparam linetype ortho

 entity categories {
    ' * 表示修飾子は必須属性を表します。 空白を1文字後ろに入れることで、強調{**}と解釈されることを防ぐと良いでしょう:
     * <<PK>> id
     --
     * name: string
 }

 entity channels {
     * <<PK>> channel_num
     --
     * <<FK>> user_id
     * <<FK>> product_id
     * purchase_date_time
     * quantity
     --
     unique : [channel_num]
 }

 entity time_slots {
     * <<PK>> product_id
     --
     * product_name
     * <<FK>> category_id
     * price
     * stock_quantity
 }

 entity series {
     * <<PK>> category_id
     --
     * category_name
 }

 categories ||--o{ channels
 channels ||..o{ time_slots
 categories ||--o{ time_slots
 @enduml