 @startuml test
 hide circle
 skinparam linetype ortho

 entity tv_schedule {
     * <<PK>> id
     --
     * <<FK>> episode_id
    '  * viewer
     * start_time
     * end_time
     * id
 }
'  entity tv_schedule {
'      * <<PK>> id
'      --
'      * <<FK>> episode_id
'      * viewer
'      * start_time
'      * end_time
'      * id
'  }

 entity channels {
     * <<PK>> channel_id
     --
     * channel_name
 }

 entity episodes {
    ' * 表示修飾子は必須属性を表します。 空白を1文字後ろに入れることで、強調{**}と解釈されることを防ぐと良いでしょう:
     * <<PK>> episode_id
     --
     * <<FK>> title_id
     * season_no
     * episode_no
     * episode_name
     * episode_details
     * video_duration
     * viewer
     * viewer
     --
     unique : [title_id]
 }

 entity programs {
     * <<PK>> title_id
     --
     * <<FK>>genre_id
     * title
 }


 episodes ||--o{ genre
 genre ||..o{ programs
 episodes ||--o{ programs
 @enduml